# Application Environment Settings
env: "staging"

environments:
  staging:
    base_url: "https://softwaredelivery-stg3.olympusmedical.com"
    users:
      software_uploader:
        username: "48200010.olympusssa.onmicrosoft.com@amer.teams.ms"
        password: "9xFXgZQR@kdgj"
      distribution_manager:
        username: "c810ef29.olympusssa.onmicrosoft.com@amer.teams.ms"
        password: "Sp0&xKgS*p4DFW"
      distribution_manager_without_permission:
        username: "gorantla.srikanth@hcltech.com"
        password: "@Srikanth6706"
      device_update_executor_without_permission:
        username: "ferozebasha.s@hcltech.com"
        password: "@Feroze123"
      device_update_executor:
        username: "26ba30ee.olympusssa.onmicrosoft.com@amer.teams.ms"
        password: "6rPB7vqX@"
      customer:
        username: "6ee6285e.olympusssa.onmicrosoft.com@amer.teams.ms"
        password: "BX6JHJ2v@"


  prod:
    base_url: "https://softwaredelivery.olympusmedical.com"
    users:
      software_uploader:
        username: "prod_uploader"
        password: "prod_uploader_password"
      distribution_manager:
        username: "prod_manager"
        password: "prod_manager_password"
base_url: "https://softwaredelivery-stg3.olympusmedical.com"
browser: "chrome" # options: chrome, edge, safari, firefox
headless: false
implicit_wait: 5
explicit_wait: 10
chrome_driver_path: "C:\\Users\\ferozebasha.s\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe"
tests:
  login:
    - username: "48200010.olympusssa.onmicrosoft.com@amer.teams.ms"
      password: "9xFXgZQR@kdgj"
      expected: "success"
upload_files:
  esg_410: "omsd_automation/uploads/ESG-410_v01.00.00.00-New_11"
db:
  server: "omsd-sqlsv-stg3.database.windows.net,1433"
  name: "omsd-sqlsv-stg3"
  username: "omsdSqlAdmin@omsd-sqlsv-stg3"
  password: "8w$Tm%-7ucNxE"
